import { readdir, unlink } from "node:fs/promises";
import path from "node:path";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

/** Removes only records and assets created by the E2E fixtures. */
export default async function globalTeardown() {
  const databaseUrl = process.env.DATABASE_URL;
  if (databaseUrl) {
    const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: databaseUrl }) });
    try {
      const phones = ["+79990000003", "+79990000004", "+79990001133", "+79990001144"];
      const orders = await prisma.order.findMany({ where: { customerPhone: { in: phones } }, select: { id: true } });
      const orderIds = orders.map((order) => order.id);
      if (orderIds.length) {
        await prisma.bonusTransaction.deleteMany({ where: { orderId: { in: orderIds } } });
        await prisma.orderItem.deleteMany({ where: { orderId: { in: orderIds } } });
        await prisma.order.deleteMany({ where: { id: { in: orderIds } } });
      }
      await prisma.reservation.deleteMany({ where: { customerPhone: { in: phones } } });
      const customers = await prisma.customer.findMany({
        where: { email: { startsWith: "e2e-" } },
        select: { id: true },
      });
      const customerIds = customers.map((customer) => customer.id);
      if (customerIds.length) {
        await prisma.bonusTransaction.deleteMany({ where: { customerId: { in: customerIds } } });
        await prisma.session.deleteMany({ where: { customerId: { in: customerIds } } });
        await prisma.authCode.deleteMany({ where: { customerId: { in: customerIds } } });
        await prisma.address.deleteMany({ where: { customerId: { in: customerIds } } });
        await prisma.customer.deleteMany({ where: { id: { in: customerIds } } });
      }
      await prisma.deliveryOption.deleteMany({ where: { name: { startsWith: "Курьер по времени " } } });
      await prisma.deliveryOption.deleteMany({ where: { name: { startsWith: "Экспресс 24/7 " } } });
    } finally {
      await prisma.$disconnect();
    }
  }

  // Upload names are generated by the app as bg-<timestamp>; retain tracked fixtures.
  const backgroundDir = path.join(process.cwd(), "content", "images", "background");
  const entries = await readdir(backgroundDir).catch(() => [] as string[]);
  await Promise.all(entries.filter((name) => name.startsWith("bg-e2e-")).map((name) => unlink(path.join(backgroundDir, name))));
}
